### ISSUE TITLE
Export from a query

### ISSUE THREAD

**Issue by synw** [handoyo/sqlitetoexcel#1]
Is it possible to export a subset of a table's data based on a sql query?

**Comment by handoyo** [comment]
Hi, 

Unfortunately it's not possible at the moment. This plugin is based on https://github.com/androidmads/SQLite2XL and i only port the available function in that library.

**Comment by synw** [comment]
I may try to create a temporary table in sql and export from there, because I really need ordering, where and join clauses for selecting data to export

**Comment by handoyo** [comment]
Let me know if you are able to get it working as your expectation.

And I will try to see if there is a way to do that, but i can't promise on the timing.
