### ISSUE TITLE
A problem occurred configuring project ':sqlitetoexcel'

### ISSUE THREAD

**Issue by Jpbroadvision** [handoyo/sqlitetoexcel#2]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':sqlitetoexcel'.
> Could not resolve all artifacts for configuration ':sqlitetoexcel:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.5.3.
     Required by:
         project :sqlitetoexcel
      > Could not resolve com.android.tools.build:gradle:3.5.3.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'.
               > dl.google.com
      > Could not resolve com.android.tools.build:gradle:3.5.3.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.3/gradle-3.5.3.pom'.
               > jcenter.bintray.com
> Could not get unknown property 'android' for project ':sqlitetoexcel' of type org.gradle.api.Project.

**Comment by Jpbroadvision** [comment]
How do I solve this error?

**Comment by handoyo** [comment]
Hi,

Sorry for late reply. Have you searched google about the gradle issue?

**Comment by Jpbroadvision** [comment]
I was able to resolve the Gradle issue. But I couldn't build my project with the sqlitetoexcel package due to AndroidManifest.xml issues. Cloning your project and running it was a success.
